// Turn data/osm.json (Overpass export, ODbL) into src/terrain/geo.js: the coastline,
// cliff lines, trail and spot heights in local metres.
// Origin is the T-Rex summit ("Puncak Kelingking", 111 m). x = east, y = north.
//   node tools/extract-osm.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const osm = JSON.parse(readFileSync(join(root, 'data/osm.json'), 'utf8'));

const ORIGIN = { lat: -8.7532187, lon: 115.4720351 };
const R = 6378137;
const kx = Math.cos((ORIGIN.lat * Math.PI) / 180) * (Math.PI / 180) * R;
const ky = (Math.PI / 180) * R;
const P = (g) => [+((g.lon - ORIGIN.lon) * kx).toFixed(2), +((g.lat - ORIGIN.lat) * ky).toFixed(2)];

const ways = osm.elements.filter((e) => e.type === 'way');
const byId = (id) => ways.find((w) => w.id === id).geometry.map(P);

// Coastline: chain the open ways end to end (OSM keeps land on the left).
const open = ways.filter((w) => w.tags.natural === 'coastline').map((w) => w.geometry.map(P));
const isClosed = (l) => l[0][0] === l.at(-1)[0] && l[0][1] === l.at(-1)[1];
const islands = open.filter(isClosed);
let pieces = open.filter((l) => !isClosed(l));
const same = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]) < 0.01;
let coast = pieces.find((p) => !pieces.some((q) => q !== p && same(q.at(-1), p[0])));
pieces = pieces.filter((p) => p !== coast);
while (pieces.length) {
  const next = pieces.find((p) => same(p[0], coast.at(-1)));
  if (!next) throw new Error('coastline chain broken');
  coast = coast.concat(next.slice(1));
  pieces = pieces.filter((p) => p !== next);
}

const nodes = osm.elements.filter((e) => e.type === 'node');
const peaks = nodes.filter((n) => n.tags.natural === 'peak').map((n) => ({ name: n.tags.name || '', ele: +n.tags.ele, p: P(n) }));
const viewpoints = nodes.filter((n) => n.tags.tourism === 'viewpoint').map((n) => ({ name: n.tags.name || String(n.id), p: P(n) }));

const out = `// Generated by tools/extract-osm.mjs from OpenStreetMap data (ODbL, (c) OpenStreetMap contributors).
// Local metres, origin at the T-Rex summit (${ORIGIN.lat}, ${ORIGIN.lon}). x = east, y = north.

export const ORIGIN = ${JSON.stringify(ORIGIN)};

// Main coastline, land on the left of travel.
export const COAST = ${JSON.stringify(coast)};

// Closed rings: the islet off the head (Batu Satu) and Batupahet further south-east.
export const ISLANDS = ${JSON.stringify(islands)};

// Cliff top lines, low side on the right of travel.
export const CLIFFS = ${JSON.stringify([byId(155739124), byId(1448397100)])};

// The descent, top to bottom.
export const TRAIL = {
  approach: ${JSON.stringify(byId(709619819))},
  pavedSteps: ${JSON.stringify(byId(1089654390).reverse())},
  ridgeSteps: ${JSON.stringify(byId(1551493016).reverse())},
  zigzag: ${JSON.stringify(byId(709619816).reverse())},
  ridgePath: ${JSON.stringify(byId(1240940208))},
};

export const PEAKS = ${JSON.stringify(peaks)};
export const VIEWPOINTS = ${JSON.stringify(viewpoints)};
`;
writeFileSync(join(root, 'src/terrain/geo.js'), out);
console.log('coast pts', coast.length, 'islands', islands.length, 'first', coast[0], 'last', coast.at(-1));
